
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jan 23 13:08:50 CET 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONT = 11;
  public static final int MAP = 15;
  public static final int CHAR = 46;
  public static final int CONST = 9;
  public static final int GRT = 35;
  public static final int REM = 32;
  public static final int LPAREN = 22;
  public static final int SEMI = 20;
  public static final int MINUS = 29;
  public static final int RPAREN = 23;
  public static final int GRE = 36;
  public static final int AND = 39;
  public static final int OR = 40;
  public static final int BOOL = 44;
  public static final int COMMA = 18;
  public static final int INC = 41;
  public static final int DIV = 31;
  public static final int PLUS = 28;
  public static final int ASSIGN = 17;
  public static final int IF = 7;
  public static final int DOT = 19;
  public static final int EOF = 0;
  public static final int RETURN = 5;
  public static final int NEW = 3;
  public static final int error = 1;
  public static final int MUL = 30;
  public static final int NUMBER = 43;
  public static final int NEQ = 34;
  public static final int IDENT = 45;
  public static final int BREAK = 6;
  public static final int VOID = 16;
  public static final int LBRACK = 24;
  public static final int COL = 21;
  public static final int EQU = 33;
  public static final int UNION = 12;
  public static final int LBRACE = 26;
  public static final int ELSE = 8;
  public static final int READ = 10;
  public static final int RBRACK = 25;
  public static final int WHILE = 14;
  public static final int LES = 37;
  public static final int RBRACE = 27;
  public static final int PROG = 2;
  public static final int LEQ = 38;
  public static final int DEC = 42;
  public static final int PRINT = 4;
  public static final int DO = 13;
}

